#!/bin/bash

# GitHub Push Helper Script
# This script helps push changes to GitHub using Personal Access Token

echo "==================================="
echo "GitHub Push Helper"
echo "==================================="
echo ""
echo "To push to GitHub, you have two options:"
echo ""
echo "Option 1: Use Personal Access Token (Recommended)"
echo "  1. Go to https://github.com/settings/tokens"
echo "  2. Click 'Generate new token' (classic)"
echo "  3. Give it a name like 'Yesra Sew Web'"
echo "  4. Select 'repo' scope"
echo "  5. Generate and copy the token"
echo "  6. Run: git push https://YOUR_TOKEN@github.com/DawitTemesgen1/yesra-sew-web-last.git main"
echo ""
echo "Option 2: Use SSH (More secure for long-term)"
echo "  1. Generate SSH key: ssh-keygen -t ed25519 -C 'dawittemesgen1@gmail.com'"
echo "  2. Add to GitHub: cat ~/.ssh/id_ed25519.pub"
echo "  3. Copy the output and add it to https://github.com/settings/keys"
echo "  4. Change remote: git remote set-url origin git@github.com:DawitTemesgen1/yesra-sew-web-last.git"
echo "  5. Push: git push origin main"
echo ""
echo "==================================="
echo "⚠️  IMPORTANT: FTP CONFIGURATION"
echo "==================================="
echo "You have enabled FTP deployment! Please ensure you add the following secret"
echo "to your GitHub Repository Settings > Secrets and variables > Actions:"
echo ""
echo "  Name: FTP_SERVER"
echo "  Value: your.ftp.server.com (or IP address)"
echo ""
echo "You already have FTP_USERNAME and FTP_PASSWORD set up."
echo ""
echo "==================================="
echo "Current Status:"
echo "==================================="
git status
echo ""
echo "==================================="
echo "Pending Commits:"
echo "==================================="
git log origin/main..HEAD --oneline
